#!/usr/bin/env python3
"""Convert the approved 64x48 one-bit PNG artwork to SSD1306 page bitmaps."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from PIL import Image


WIDTH = 64
HEIGHT = 48
PAGES = HEIGHT // 8
FRAME_BYTES = WIDTH * PAGES
ASSETS = (
    ("cancel.png", "oled_image_cancel"),
    ("confirm.png", "oled_image_confirm"),
    ("coocking.png", "oled_image_cooking"),
    ("error.png", "oled_image_error"),
    ("nopan.png", "oled_image_no_pan"),
    ("ready.png", "oled_image_ready"),
    ("sleep1.png", "oled_image_sleep_warning"),
    ("sleep2.png", "oled_image_sleep"),
    ("turnon.png", "oled_image_turn_on"),
    ("wakeup.png", "oled_image_wakeup"),
)


def frame_from_png(path: Path) -> tuple[bytes, str]:
    with Image.open(path) as source:
        if source.size != (WIDTH, HEIGHT) or source.mode != "1":
            raise ValueError(f"{path}: expected {WIDTH}x{HEIGHT} mode 1, got {source.size} {source.mode}")
        image = source.copy()

    # error.png contains an example E03 plus a separator stroke in the lower-right
    # corner. Keep the approved source untouched and reserve that entire corner
    # for the live 2x fault code so no part of the separator remains visible.
    if path.name == "error.png":
        for y in range(30, 48):
            for x in range(30, 64):
                image.putpixel((x, y), 0)

    output = bytearray(FRAME_BYTES)
    for page in range(PAGES):
        for x in range(WIDTH):
            value = 0
            for bit in range(8):
                if image.getpixel((x, page * 8 + bit)):
                    value |= 1 << bit
            output[page * WIDTH + x] = value
    return bytes(output), hashlib.sha256(path.read_bytes()).hexdigest()


def format_array(name: str, frame: bytes, source_name: str, digest: str) -> str:
    rows = []
    for start in range(0, len(frame), 16):
        values = ", ".join(f"0x{value:02x}" for value in frame[start : start + 16])
        rows.append(f"    {values},")
    return (
        f"/* {source_name}; source SHA-256 {digest} */\n"
        f"const uint8_t {name}[OLED_ASSET_FRAME_BYTES] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def generate(input_dir: Path) -> tuple[str, str]:
    declarations = []
    definitions = []
    for filename, symbol in ASSETS:
        frame, digest = frame_from_png(input_dir / filename)
        declarations.append(f"extern const uint8_t {symbol}[OLED_ASSET_FRAME_BYTES];")
        definitions.append(format_array(symbol, frame, filename, digest))

    header = """#pragma once

#include <stdint.h>

#define OLED_ASSET_WIDTH 64U
#define OLED_ASSET_HEIGHT 48U
#define OLED_ASSET_FRAME_BYTES 384U

""" + "\n".join(declarations) + "\n"
    source = (
        "/* Generated by tools/generate_oled_assets.py; do not edit by hand. */\n"
        '#include "oled_assets.h"\n\n'
        + "\n".join(definitions)
    )
    return header, source


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    script = Path(__file__).resolve()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=script.parents[3] / "assets" / "images" / "oled-64x48",
    )
    parser.add_argument("--output", type=Path, default=script.parents[1] / "main")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    header, source = generate(args.input.resolve())
    expected = {
        args.output.resolve() / "oled_assets.h": header,
        args.output.resolve() / "oled_assets.c": source,
    }
    if args.check:
        stale = [path for path, content in expected.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit("Stale OLED assets: " + ", ".join(str(path) for path in stale))
        print(f"OLED assets: PASS ({len(ASSETS)} images, {len(ASSETS) * FRAME_BYTES} bytes)")
        return 0

    args.output.resolve().mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        write_if_changed(path, content)
    print(f"Generated {len(ASSETS)} OLED images ({len(ASSETS) * FRAME_BYTES} raw bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
