/* Generated by sound_design/generate_previews.py. */
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t frequency_hz;
    uint16_t on_ms;
    uint16_t gap_ms;
} buzzer_note_t;

/* Power on / Korobeiniki; 4.800 s. */
static const buzzer_note_t k_sound_boot[] = {
    {2637, 240, 20},
    {1976, 120, 20},
    {2093, 120, 20},
    {2349, 240, 20},
    {2093, 120, 20},
    {1976, 120, 20},
    {1760, 240, 20},
    {1760, 120, 20},
    {2093, 120, 20},
    {2637, 240, 20},
    {2349, 120, 20},
    {2093, 120, 20},
    {1976, 300, 40},
    {2093, 120, 20},
    {2349, 240, 20},
    {2637, 240, 20},
    {2093, 240, 20},
    {1760, 240, 40},
    {1760, 360, 120},
    {2637, 80, 20},
    {3136, 80, 20},
    {3951, 80, 20},
    {5274, 320, 0},
    {0, 0, 0},
};

/* Cooking complete / When the Saints; 4.290 s. */
static const buzzer_note_t k_sound_complete[] = {
    {2093, 120, 30},
    {2637, 120, 30},
    {2794, 120, 30},
    {3136, 300, 80},
    {2093, 120, 30},
    {2637, 120, 30},
    {2794, 120, 30},
    {3136, 300, 80},
    {2093, 120, 30},
    {2637, 120, 30},
    {2794, 120, 30},
    {3136, 200, 30},
    {2637, 120, 30},
    {2093, 120, 30},
    {2637, 140, 30},
    {2349, 260, 80},
    {2637, 100, 20},
    {2349, 100, 20},
    {2093, 140, 40},
    {2637, 100, 20},
    {3136, 100, 20},
    {4186, 480, 0},
    {0, 0, 0},
};

#include "melody_nutcracker.generated.h"

/* Critical / Beethoven Fifth; 2.500 s. */
static const buzzer_note_t k_sound_critical[] = {
    {3951, 140, 40},
    {3951, 140, 40},
    {3951, 140, 40},
    {3136, 520, 120},
    {3520, 140, 40},
    {3520, 140, 40},
    {3520, 140, 40},
    {2960, 520, 120},
    {4000, 140, 0},
    {0, 0, 0},
};

/* Sleep / Low-register Twinkle; 4.940 s. */
static const buzzer_note_t k_sound_sleep[] = {
    {523, 260, 60},
    {523, 260, 60},
    {784, 260, 60},
    {784, 260, 60},
    {880, 260, 60},
    {880, 260, 60},
    {784, 500, 100},
    {698, 260, 60},
    {698, 260, 60},
    {659, 260, 60},
    {659, 260, 60},
    {587, 260, 60},
    {587, 260, 60},
    {523, 500, 0},
    {0, 0, 0},
};

/* Wake / Simple bright arpeggio; 1.850 s. */
static const buzzer_note_t k_sound_wake[] = {
    {2093, 160, 40},
    {2637, 160, 40},
    {3136, 160, 40},
    {4186, 240, 100},
    {3136, 100, 30},
    {4186, 100, 30},
    {5274, 650, 0},
    {0, 0, 0},
};

/* Integration targets: normal sounds 50%, sleep about 18% PWM duty. */
#define SELECTED_SOUND_NORMAL_DUTY_PERMILLE 500U
#define SELECTED_SOUND_SLEEP_DUTY_PERMILLE  180U
