#!/usr/bin/env python3
"""Pack every 64x48 one-bit PNG in a directory for an SSD1306 OLED."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

from PIL import Image


WIDTH = 64
HEIGHT = 48
PAGES = HEIGHT // 8
FRAME_BYTES = WIDTH * PAGES


def symbol_from_stem(stem: str) -> str:
    """Return a stable C identifier derived from a PNG filename stem."""
    normalized = re.sub(r"[^0-9A-Za-z]+", "_", stem).strip("_").lower()
    if not normalized:
        raise ValueError(f"Cannot derive a C symbol from {stem!r}")
    if normalized[0].isdigit():
        normalized = f"image_{normalized}"
    return f"oled_image_v2_{normalized}"


def frame_from_png(path: Path) -> bytes:
    """Convert a mode-1 PNG to the page-major byte order used by SSD1306."""
    with Image.open(path) as source:
        if source.size != (WIDTH, HEIGHT) or source.mode != "1":
            raise ValueError(
                f"{path}: expected {WIDTH}x{HEIGHT} mode 1, "
                f"got {source.size} {source.mode}"
            )
        image = source.copy()

    output = bytearray(FRAME_BYTES)
    for page in range(PAGES):
        for x in range(WIDTH):
            value = 0
            for bit in range(8):
                if image.getpixel((x, page * 8 + bit)):
                    value |= 1 << bit
            output[page * WIDTH + x] = value
    return bytes(output)


def format_array(name: str, frame: bytes, source_name: str, digest: str) -> str:
    rows = []
    for start in range(0, len(frame), 16):
        values = ", ".join(f"0x{value:02x}" for value in frame[start : start + 16])
        rows.append(f"    {values},")
    return (
        f"/* {source_name}; source SHA-256 {digest} */\n"
        f"const uint8_t {name}[OLED_ASSET_V2_FRAME_BYTES] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def generate(input_dir: Path) -> tuple[str, str, int]:
    source_paths = sorted(input_dir.glob("*.png"), key=lambda path: path.name.lower())
    if not source_paths:
        raise ValueError(f"No PNG files found in {input_dir}")

    assets: list[tuple[str, str, bytes, str]] = []
    symbols: set[str] = set()
    for path in source_paths:
        symbol = symbol_from_stem(path.stem)
        if symbol in symbols:
            raise ValueError(f"Duplicate generated symbol {symbol} for {path.name}")
        symbols.add(symbol)
        assets.append(
            (
                path.name,
                symbol,
                frame_from_png(path),
                hashlib.sha256(path.read_bytes()).hexdigest(),
            )
        )

    declarations = [
        f"extern const uint8_t {symbol}[OLED_ASSET_V2_FRAME_BYTES];"
        for _, symbol, _, _ in assets
    ]
    entries = [
        f'    {{"{filename}", {symbol}}},'
        for filename, symbol, _, _ in assets
    ]
    definitions = [
        format_array(symbol, frame, filename, digest)
        for filename, symbol, frame, digest in assets
    ]

    header = f"""#pragma once

#include <stddef.h>
#include <stdint.h>

#define OLED_ASSET_V2_WIDTH {WIDTH}U
#define OLED_ASSET_V2_HEIGHT {HEIGHT}U
#define OLED_ASSET_V2_FRAME_BYTES {FRAME_BYTES}U
#define OLED_ASSET_V2_COUNT {len(assets)}U

typedef struct {{
    const char *filename;
    const uint8_t *frame;
}} oled_asset_v2_entry_t;

""" + "\n".join(declarations) + "\n\n" + """extern const oled_asset_v2_entry_t
    oled_assets_v2[OLED_ASSET_V2_COUNT];
"""
    source = (
        "/* Generated by tools/image/generate_oled_asset_pack.py; "
        "do not edit by hand. */\n"
        '#include "oled_assets_v2.h"\n\n'
        + "\n".join(definitions)
        + "\nconst oled_asset_v2_entry_t oled_assets_v2[OLED_ASSET_V2_COUNT] = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    return header, source, len(assets)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    input_dir = args.input.resolve()
    output_dir = args.output.resolve()
    header, source, count = generate(input_dir)
    expected = {
        output_dir / "oled_assets_v2.h": header,
        output_dir / "oled_assets_v2.c": source,
    }

    if args.check:
        stale = [
            path
            for path, content in expected.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            raise SystemExit("Stale OLED V2 assets: " + ", ".join(map(str, stale)))
        print(f"OLED V2 assets: PASS ({count} images, {count * FRAME_BYTES} bytes)")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        write_if_changed(path, content)
    print(f"Generated {count} OLED V2 images ({count * FRAME_BYTES} raw bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
